### ISSUE TITLE
Updating arXiv paper does not seem to update the meta data.

### ISSUE THREAD

**Issue by dschaehi** [AllanChain/zotero-arxiv-workflow#12]
If I have an old arXiv paper entry in the Zotero database and I update the PDF by selecting "Update arXiv paper" from the context menu, the metadata is not updated even though the PDF is updated. I am wondering whether this an intended behavior. Thanks.

**Comment by AllanChain** [comment]
Thanks for reporting. This is a bug. Can you elabrate which fields are you expected to be updated?

**Comment by dschaehi** [comment]
I think the "date" field of the paper needs to be updated at least to the newer version. I can imagine that the authors' names or the order of authors may have changed in the newer versions as well. So I would actually update all fields to the latest version.
If the Zotero entry is a merged paper that contains both the published and arXiv versions, the metadata does not need to be updated because the metadata is based on the published version, which should remain unchanged.
