### ISSUE TITLE
The published paper information is not updated through Semantic Scholar API

### ISSUE THREAD

**Issue by wjfu99** [AllanChain/zotero-arxiv-workflow#13]
Recently, i tried to update a published paper "Fast-DetectGPT: Efficient Zero-Shot Detection of Machine-Generated Text via Conditional Probability Curvature" through your plugin. I have ensured that the published info of this paper appear in Semantic Scholar: https://www.semanticscholar.org/paper/Fast-DetectGPT%3A-Efficient-Zero-Shot-Detection-of-Bao-Zhao/85664bb73d09a20f4d3f7aae81143c0f25060fbb
<img width="807" alt="image" src="https://github.com/user-attachments/assets/059fe162-5636-4fe3-be93-dbc8e6ae36ae">

But the plugin seems to only add a newer version PDF not update the metadata. I also notice a commit had been made to rewrite the update function and add dblp.org, i hope this will make the workflow works fine.

**Comment by AllanChain** [comment]
Thanks for reporting. I didn't release a new version that includes 3cd9103 because I didn't have time to deal with the potential bug reports last two weeks.

Just released v0.2.4 to fix this.
