### ISSUE TITLE
Avoid Updating arXiv Preprints to CoRR in dblp.org Data

### ISSUE THREAD

**Issue by seifer08ms** [AllanChain/zotero-arxiv-workflow#14]
Dear Authors,

Thank you for the recent update that includes dblp.org data, which have significantly improved the recognition and categorization of published papers. However, I've noticed that some arXiv preprints are being incorrectly updated as CoRR journal articles instead of retaining their preprint type due to this update.

Could you consider an exception for dblp.org's CoRR entries to prevent such misclassifications?

FYI:
dblp only indexes arXiv papers that belong to a cs.* subject category (as "The Computing Research Repository", CoRR).

**Comment by seifer08ms** [comment]
Here is an example that rapidly reproduces this issue : https://arxiv.org/abs/2312.02228.

**Comment by AllanChain** [comment]
Thanks for reporting. But I'm not very familiar with CS. Is it better to ignore the entry if the DOI contains "ARXIV", or should we ignore `CoRR` all together?

Here is the response from dblp.org:
```json
{
  "authors": {
    "author": [
      ...
    ]
  },
  "title": "PixelLM: Pixel Reasoning with Large Multimodal Model.",
  "venue": "CoRR",
  "volume": "abs/2312.02228",
  "year": "2023",
  "type": "Informal and Other Publications",
  "access": "open",
  "key": "journals/corr/abs-2312-02228",
  "doi": "10.48550/ARXIV.2312.02228",
  "ee": "https://doi.org/10.48550/arXiv.2312.02228",
  "url": "https://dblp.org/rec/journals/corr/abs-2312-02228"
}
```

**Comment by seifer08ms** [comment]
> Thanks for reporting. But I'm not very familiar with CS. Is it better to ignore the entry if the DOI contains "ARXIV", or should we ignore `CoRR` all together?
> 
> Here is the response from dblp.org:
> 
> ```json
> {
>   "authors": {
>     "author": [
>       ...
>     ]
>   },
>   "title": "PixelLM: Pixel Reasoning with Large Multimodal Model.",
>   "venue": "CoRR",
>   "volume": "abs/2312.02228",
>   "year": "2023",
>   "type": "Informal and Other Publications",
>   "access": "open",
>   "key": "journals/corr/abs-2312-02228",
>   "doi": "10.48550/ARXIV.2312.02228"  ,
>   "ee": "https://doi.org/10.48550/arXiv.2312.02228",
>   "url": "https://dblp.org/rec/journals/corr/abs-2312-02228"
> }
> ```
Since dblp exclusively indexes CS paper and CoRR is a CS subset of arXiv, all arXiv entries on dblp are considered CoRR. The result should be equivalent whether the judgment is based on the inclusion of "ARXIV" in the DOI or on whether it is a CoRR journal.

If so, only the DOI information should be appended to the arXiv entry, while other details, particularly the preprint type, should remain unchanged. 

Alternatively, information from dblp regarding arXiv or CoRR could be entirely ignored. Given that the DOI format for arXiv is standardized, conforming to the pattern 10.48550/ARXIV.XXXX, there is no need to update the DOI from dblp, instead, DOI information can be autonomously generated by the fixed pattern.   I personally lean towards the second approach, and when the arXiv DOI is absent, it can be automatically filled. The capability to generate the DOI could be offered as an optional setting for users to select at their discretion.

FYI:  In fact, DOIs are useful, as they are required by certain journals for the citation of arXiv preprints.

**Comment by AllanChain** [comment]
I agree. Now, the plugin does nothing when it sees CoRR from DBLP.

As for DOI for arXiv papers, I think the newest Zotero connector will automatically add it.
