### ISSUE TITLE
Unable to actually update the pdf attachment after clicking "Update arxiv paper"

### ISSUE THREAD

**Issue by Fusionplay** [AllanChain/zotero-arxiv-workflow#15]
My ordinary use case of this plugin is to simply update to the latest **arxiv version** of the paper. But when I click "Update arxiv paper", the plugin only updates the metadata of the item according to the arxiv page info, and does not actually download the latest arxiv pdf file and replace the old one.

macOS 14.4.1 (23E224)
zotero: 7.0.6-beta.2+b4239fd4c
plugin version: 0.2.5

**Comment by AllanChain** [comment]
Thanks for reporting this issue.

The current behavior is to update the metadata and try to download the PDF from the publisher. But many conferences do not provide a link to download the PDF, and the download will fail.

In case I misunderstood your idea, are you suggesting that we should provide an option to ignore those conference metadata and just update the PDF from arxiv.org? Or should we fall back to update the PDF from arxiv.org if we fail to download from the publisher?

**Comment by Fusionplay** [comment]
Thanks for the timely response. Yes, I'm suggesting the following new feature:
Ignore the publishing stuff. Fetch the latest metadata, and the latest pdf, only from arxiv. The downloaded latest pdf could co-exist with the old one under the same item, or replace the old one. This could be a checkbox option to be customized by user.

Many papers keep updating on arxiv even after published, so this new feature would be pratical for those who want to always read the latest content.

**Comment by AllanChain** [comment]
The latest commit 2ced273 made it possible to disable some update sources. In your case, disabling all sources except "arXiv PDF" should work.

![image](https://github.com/user-attachments/assets/610fb694-3476-42c1-9de4-1c6925451edf)

**Comment by Fusionplay** [comment]
Hi, after updating to 0.2.6 and disabling all sources except "arXiv PDF", "Update arxiv paper" still does not function well. In many cases, after popping up "update succeeded", the latest pdf is not downloaded.

An example:
Before update: the pdf is the v1 version
![image](https://github.com/user-attachments/assets/109ac2e6-3ef8-4892-aa82-060a8290ba21)

After update: The pdf file remains the same v1 version. I checked it. Not the latest v4 version. A snapshot is downloaded instead of the latest pdf.
![image](https://github.com/user-attachments/assets/da5f0b03-5825-428f-9d8e-12879ba9d811)

The arxiv link to the example: [Show-o: One Single Transformer to Unify Multimodal Understanding and Generation](http://arxiv.org/abs/2408.12528)
And the URL field of the item does not contain "v1|v2" postfix.
