### ISSUE TITLE
Unable to display functions in the right-click menu

### ISSUE THREAD

**Issue by A-PolarBear** [AllanChain/zotero-arxiv-workflow#16]
Hello, Thanks for your effort to provide this awesome plugin that meets my demand!  But unfortunately, when I installed the plugin, it didn't work. The plugin cannot display the corresponding functions in the right-click menu. My Zotero version is 7.0.8-beta.2+237a2e5b8 (64-bit).
![image](https://github.com/user-attachments/assets/dec0fd89-ffbc-4d63-a41d-476ae0b858e4)

**Comment by AllanChain** [comment]
I can't reproduce these. Can you see the settings of the plugin? Can you try to reinstall the plugin?
![image](https://github.com/user-attachments/assets/36d65a87-be96-4c0b-bc80-23cb4e9fff41)

**Comment by A-PolarBear** [comment]
I have attempted to reinstall the plugin, but it has not made any difference. And here is the settings page.
![image](https://github.com/user-attachments/assets/76cad944-92a5-4275-b206-e4066a1593fb)

**Comment by A-PolarBear** [comment]
Here is the plugins page.
![image](https://github.com/user-attachments/assets/f9f8d858-79b0-4f10-bb6e-c93028366ba6)

**Comment by AllanChain** [comment]
That's weird. Can you go to "Tools" → "Developer" → "Error Console" and search for "arxiv"? Are there any errors logged?

Normally, it should look like
<img width="894" alt="Screenshot 2024-10-13 at 10 50 51" src="https://github.com/user-attachments/assets/58ea61fd-3c8c-487e-842b-935907ac5aac">

**Comment by A-PolarBear** [comment]
Yep, there are some error logs about this plugin.
![image](https://github.com/user-attachments/assets/894f2086-aa23-47e0-9a07-02343d12acca)

**Comment by AllanChain** [comment]
To be honest, I have no idea why this happens. What I've done is to upgrade to the latest version of template.

Can you try the latest build on `main` branch (https://github.com/AllanChain/zotero-arxiv-workflow/actions/runs/11311511959/artifacts/2049619304) and see if the plugin works?

PS: The latest version is not well tested and may have some bugs. But it will be a good news if you are able to see the plugin settings and menus.

**Comment by A-PolarBear** [comment]
That's brilliant! The plugin is finally working properly. Thank you very much for helping me solve this problem！
