### ISSUE TITLE
Adapt for other preprint services like bioRxiv and PsyArXiv?

### ISSUE THREAD

**Issue by huachuman** [AllanChain/zotero-arxiv-workflow#20]
Any way to do this?

**Comment by AllanChain** [comment]
I think you mean the feature to search for updated version of an arXiv paper? Other features should work regardless of the exact preprint platform.

For updating arXiv paper, this plugin use 4 different sources:
- Related DOI field on arxiv.org
- Semantic scholar by searching arXiv ID
- DBLP by search exact title match
- Fallback to find updated version of PDF on arXiv

To support other preprint services, maybe we can first support the first source, namely finding publish information on the corresponding page. For example, bioRxiv and medRxiv have API for published entries:
- https://api.biorxiv.org/details/biorxiv/10.1101/2020.03.24.997536
- https://api.medrxiv.org/details/medrxiv/10.1101/2021.12.22.21268268
But for PsyArXiv, I failed to find related information.

**Comment by AllanChain** [comment]
An initial implementation is available at https://github.com/AllanChain/zotero-arxiv-workflow/actions/runs/11818971474/artifacts/2182221382. You can test it before I include it in a stable release.
