### ISSUE TITLE
Library and collection information is lost after updating to published version

### ISSUE THREAD

**Issue by peixinshen** [AllanChain/zotero-arxiv-workflow#21]
Hi! Thank you so much for developing this incredibly useful addon! I particularly appreciate the “Prefer this PDF” feature, which streamlines the default opening PDF.

I have encountered an issue where, after using the addon to update an arXiv paper to its published version, the new combined item loses its information about Libraries and Collections. Since Zotero allows items to belong to multiple Libraries and Collections, it would be helpful if the updated item could retain this information.

Additionally, if possible, I would like to suggest an option to choose whether to keep the “Preprint URL” and “Extra arXiv:XXXX.XXXXX” fields in the updated item. This would add more flexibility in managing the metadata for different use cases.

Thank you for your hard work on this addon, and for continually improving the Zotero experience!

**Comment by AllanChain** [comment]
> I have encountered an issue where, after using the addon to update an arXiv paper to its published version, the new combined item loses its information about Libraries and Collections. Since Zotero allows items to belong to multiple Libraries and Collections, it would be helpful if the updated item could retain this information.

Thanks for reporting. That is not expected and should be a bug. However, I can't reproduce it. Could you share reproducible steps?

**Comment by seifer08ms** [comment]
> > I have encountered an issue where, after using the addon to update an arXiv paper to its published version, the new combined item loses its information about Libraries and Collections. Since Zotero allows items to belong to multiple Libraries and Collections, it would be helpful if the updated item could retain this information.
> 
> Thanks for reporting. That is not expected and should be a bug. However, I can't reproduce it. Could you share reproducible steps?

I have also encountered the issue of losing collection information, but it seems that this problem occurs randomly.

**Comment by AllanChain** [comment]
I'm able to reproduce this now and fixed it in https://github.com/AllanChain/zotero-arxiv-workflow/commit/974932df0209d50ab1bd9632c865c38ba311d6aa.

Accidentally, the collection info of the arXiv paper item was overwritten by the published item. The old code worked fine previously, if the arXiv paper is in only one collection, and we click "update" in that collection.
