### ISSUE TITLE
"Archive ID" field

### ISSUE THREAD

**Issue by kelawson48** [AllanChain/zotero-arxiv-workflow#22]
New field "Archive ID" is showing in citations and repeats information when citing, as well as having awkward wording ("No. aXiv:....", see APA ref example below). Is this add-on the one creating this field? I disabled the add-on but the field remains for all my preprints and I don't know how to get rid of it other than manually clearing the field for every single preprint. I'd ignore it, except that it is showing in the reference lists of the proposals and papers I manage for my research lab, which is... inconvenient. 

APA citation shown below, and screenshot of add-ons I am using (as far as I can tell, this is the only one that would be likely to add this field)

Bodnar, C., Bruinsma, W. P., Lucic, A., Stanley, M., Brandstetter, J., Garvan, P., Riechert, M., Weyn, J., Dong, H., Vaughan, A., Gupta, J. K., Tambiratnam, K., Archibald, A., Heider, E., Welling, M., Turner, R. E., & Perdikaris, P. (2024). Aurora: A foundation model of the atmosphere (No. arXiv:2405.13063). arXiv.[ https://doi.org/10.48550/arXiv.2405.13063](https://doi.org/10.48550/arXiv.2405.13063)

![image](https://github.com/user-attachments/assets/2298fb98-c710-4317-bb02-aea5a30cc9d9)

**Comment by AllanChain** [comment]
Do you mean you are citing an item which has been published, and getting "No. arXiv:...."? Or are you citing an arXiv paper? This plugin does not automatically add field "Archive ID" for arXiv papers. This seems a built-in feature in Zotero.

**Comment by kelawson48** [comment]
Thank you for your quick response and confirming that this add-on doesn't add the field! I am citing an arXiv paper and getting "No. arXiv:...." so I guess I'll need to post to the Zotero forums for more info.

**Comment by AllanChain** [comment]
I'm closing this issue as not planned because it is related to Zotero itself. But feel free to reopen this issue or create new issues if you find something that should be done on the plugin side.
