### ISSUE TITLE
[feature request] customized merge rules

### ISSUE THREAD

**Issue by falbarelli** [AllanChain/zotero-arxiv-workflow#24]
Thanks a lot for this nice plugin! It makes me *extremely* close to fully automating my daily workflow... however I have used a slightly different merging rule so far and I would like to keep consistency in my database. Would it be hard to have the possibility to customize how metadata is merged?

More specifically, I want to keep the arXiv URL.
The DOI is already a link, which is meant to be permanent, while the URL scheme of the journal may change in the future. Moreover the link that appears in the rendered reference (e.g. in RevTeX and bibtex) is the one in the DOI field, not the one in the URL field.

The other thing I do is to delete the arXiv pdf if it contains no annotations, but I understand this change might be much more involved to implement.

A couple of comments on the README. 
I think the "main logic" scheme in the "How?" section is incorrect, the merged file should have URL (B) not URL (A) (which is what I want to do).
It would also be good to mention that the "Extra" field is populated from the arXiv version, which is I think the correct behavior, since it contains the arXiv ID.

**Comment by AllanChain** [comment]
Thank you for bringing up this issue. I assume you are focused on the Computer Science field, which often differs from other research areas. CS researchers typically prioritize finding papers on arXiv, with conference information serving as supplementary, while others may prefer published journal versions. In my opinion, this plugin should first target at a broader audience.

### For a broader audience:

> More specifically, I want to keep the arXiv URL.

The initial implementation of this plugin preserves the arXiv URL. However, this can be problematic as some citation styles (e.g., Vancouver) include the URL. Instead, this plugin preserves the snapshot item or creates a preprint URL item. Perhaps you can explain why you prefer the URL field over a URL item.

> I think the "main logic" scheme in the "How?" section is incorrect, the merged file should have URL (B) not URL (A) (which is what I want to do).

Apologies for the inconsistency. This was historically accurate but does not match the current behavior.

> It would also be good to mention that the "Extra" field is populated from the arXiv version, which is I think the correct behavior, since it contains the arXiv ID.

The extra field is indeed handled incorrectly. The `arXiv:` info should be removed, and any information for the published item should be preserved.

> The other thing I do is to delete the arXiv pdf if it contains no annotations, but I understand this change might be much more involved to implement.

This could be an option.

### For CS researchers:

> I want to keep the arXiv URL

This could be an option. However, I need more context to understand your preference.

> "Extra" field is populated from the arXiv version, which is I think the correct behavior, since it contains the arXiv ID.

I can add an option to preserve the arXiv ID in the extra field, but I need more context on the motivation behind this.

**Comment by falbarelli** [comment]
Hi! Thanks for taking the time to reply carefully to my suggestions, comments and requests.

Actually, I don't work in CS, I work in quantum physics, but I don't think my workflow is representative of any particular community. The bigger point I wanted to make is that different people may have slightly different preferences, and if the plugin allowed the possibility of tweaking manually the merge process it would be an even more useful tool.

In my case, I have already adopted my merging scheme on hundreds (or more) of papers, and keeping internal consistency in my database is probably my main concern.

One reason why I adopted this scheme is that the Zotero translator for arXiv.org used to behaved this way for published documents (i.e. with a "Related DOI" field). It used to create a Zotero item by populating the metadata from the "Related DOI", but it would keep the arXiv URL as well as the arXiv ID in the "Extra" field. Now the behavior has changed and even if the preprint has been published it doesn't fetch any information from the related DOI.

More fundamentally, the reason why I don't care at all about the URL of the published paper is that it is redundant information. First, the DOI field in Zotero is already a clickable link. Second, when I export the bibliography in a bibTeX file using BetterBibTeX, and then write a paper using REVTeX for example, the clickable link in the bibliography entry of the compiled PDF points to the DOI in URL form (https://doi.org/...). As I already mentioned, the DOI is essentially a permanent link, while regular links to the publisher's website may experience link rot.

I also think it's really useful to keep the arXiv ID in the "Extra" field. When it is present, exporting the item in a bibtex file with BetterBibTeX creates an entry with the "eprint" and "archiveprefix" fields, beyond the regular "journal", "volume", etc.
This is extremely useful because it gives me the possibility to have a bibliography entry with the details of the published version, while also keeping a link to the arXiv version. This is extremely handy for quickly checking a paper without access to the paywalled versions, and it's a little habit that has been commented positively by some of my collaborators.

I hope this makes my motivations clear. I would like to be more helpful concretely and work on these modifications myself, but this is beyond my coding abilities for the moment.

**Comment by AllanChain** [comment]
I understand your perspective. While including arXiv links is beneficial when sending notes to collaborators, it can present challenges when writing a paper. Unfortunately, accommodating both use cases simultaneously seems impractical, and I believe we should prioritize paper writing. If you have suggestions on how to support both scenarios, please share.

Regarding preserving the arXiv URL, I'm not entirely clear on your point. The arXiv URL is not lost; it is stored under "arXiv.org Snapshot" or "Preprint URL". Furthermore, some citation styles, like Vancouver, use the URL field to create a clickable link. Therefore, I don't see a need to set the URL field specifically to the arXiv link.

**Comment by falbarelli** [comment]
Thanks for taking the time to consider my perspective.

I do not agree that including the arXiv links is beneficial only when sending notes to collaborators. I think it is also very useful when uploading the paper on arXiv itself too. It is unfortunately not very common, but I do enjoy the arXiv ID is included in addition the reference to the published version. See an example I read recently https://arxiv.org/abs/2404.16101 
While it's true that everything is just a google search away, when the arXiv ID also contains a hyperlink (unfortunately not the case in the example above) then the arXiv version is just 2 clicks away. From a broader perspective, I see this as a practice that fosters sharing of knowledge and openness, since the arXiv version is freely accessible by everybody.

You are right that many journals will not accept the arXiv link for published papers, but this is not true for all journals. For example the arXiv overlay journal [Quantum](https://quantum-journal.org/) allows you to do almost whatever you want with the bibliography, as long as DOI links for published references are included. 
More generally, it's important to keep in mind that a scientific manuscript has a life that extends beyond the published version on the journal's website. First, it often appears on the arXiv long before publication; second, even after publication many people read the arXiv version due to paywalls.

I agree that your merge procedure preserves the arXiv URL, but it is not stored in a way that is usable with the BetterBibTeX plugin, as far as I know, which instead relies on the arXiv ID being stored in the Extra field. I appreciate that  that some citation styles use the URL field, and I am not suggesting to make my approach the default one, but I am sure I am not the only one who may wish to export bibtex files with both journal reference and the "eprint" and "archiveprefix" fields. 

My suggestion would be to simply have a few more settings to choose from in the "arXiv workflow" panel of the Zotero Settings. For my particular needs, it would be enough to have two additional true-false toggles, which should be "False" by default:
[ ] Use Extra field from arXiv version
[ ] Use URL field from arXiv version instead of creating Web Link attachment. 
Overall, I think it would be a minimal change to your plugin, but still it would enhance the usability for people who want to achieve results similar to mine, in particular the first toggle would be useful for people who use BetterBibTeX for creating bibliographies.

**Comment by AllanChain** [comment]
I got your point. It is a minor change, but it's important to inform the user that it may cause some bibliography styles to include arXiv information and links. If the user does not want these links, they will be responsible for removing them manually.

**Comment by falbarelli** [comment]
> I got your point. It is a minor change, but it's important to inform the user that it may cause some bibliography styles to include arXiv information and links. If the user does not want these links, they will be responsible for removing them manually.

Thanks again, both for implementing my queries so quickly and more generally for your work on this very useful plugin :)
