### ISSUE TITLE
Add item as preprint rather than journal article

### ISSUE THREAD

**Issue by kelawson48** [AllanChain/zotero-arxiv-workflow#25]
Is it possible to have items added as type "preprint" instead of "journal article" until they are published? Right now, they default to "journal article".

**Comment by AllanChain** [comment]
Can you provide more details? I can't get your point. This plugin doesn't "add" items, I think. Do you mean adding an item using Zotero connector? Or are you adding an item by dropping a PDF file?

**Comment by peixinshen** [comment]
This could be a bug in the Release v0.2.9. After the "preprint" is updated, the old item is modified to "journal article" while the new item is also "added" as a "journal article". These two items exist simultaneously and do not merge automatically. I did not encounter this problem in Release v0.2.8.
