### ISSUE TITLE
What is the preferred workflow of this plugin?

### ISSUE THREAD

**Issue by mjthoraval** [AllanChain/zotero-arxiv-workflow#3]
Thank you very much for the plugin.

The way Zotero deals with arXiv papers is a mess:
https://forums.zotero.org/discussion/109803/zotero-7-arxiv-submission-version-is-ignored
And people have different expectations on how to deal with arXiv papers that have been finally published:
https://forums.zotero.org/discussion/99045/zotero-connector-arxiv-treated-as-publication

Do you keep only one parent item for all the different PDF files, including the final publication and the different arXiv versions, or do you keep them as separate items and relate them?
Do you keep some of the metadata from the arXiv version in the merged item, or do you keep only the metadata of the final publication?
Do you move the URL of the arXiv version to a Web Link attachment, do you keep it as the main URL, or do you delete it?

Could you add a screenshot of an example, showing the state before merging, and what you see after merging?
And also for updating an arXiv item that has been published.

**Comment by AllanChain** [comment]
Thanks for pointing out. The README should definitely be improved. For the questions:
- My workflow is to keep only one parent item for both the arXiv and published version. Because, AFAIK, Zotero doesn't have the functionality to smoothly link different items.
- I use the metadata from the published version, because I'll only need the information from the published version to cite. But I keep the arXiv link in the URL page in case I want to share the paper with someone without access to the full text paper.
- It's a good idea to provide an alternative way to treat the URLs, as you mentioned.

It can help a lot for people to understand what this plugin does with more screenshots, and I will add them. In short:
```
Before:                     After:
==================          ==================
Item A (published)          Item B
------------------          ------------------
Metadata A                  Metadata A
------------------          (URLs from B)
PDF attachment a            ------------------
more attachments            PDF attachment a
==================          more attachments
Item B (arXiv)              PDF attachment b*
------------------          ==================
Metadata B
------------------          * means prefered PDF
PDF attachment b
more attachments
==================
```

Updating a paper is quite similar. The plugin find and adds the published item automatically, and the merge logic is the same.

Please tell me if there's anything unclear so that I can improve the description.

**Comment by mjthoraval** [comment]
Thank you for the explanations.
So I understand that the main purpose of the plugin is to keep one single item from early publication on arXiv until final publication:
- Merging ensures that the citations will be updated to the final publication when available, and that other Zotero plugins will connect to the updated item and metadata.
- You usually do not need to cite the arXiv version after final publication, so you do not need to keep the arXiv item separately, keeping a cleaner library.
- You keep all the files together, so that you can see the earlier arXiv version and eventual annotations you have made on them.
- And you also keep the URL of the arXiv version to keep track of earlier versions and allow easier access to the open access version when needed.

> Zotero doesn't have the functionality to smoothly link different items.

It is possible to link different items with the "Related" functionality.
You can do it from the right-click menu with the Actions and Tags plugin: https://github.com/windingwind/zotero-actions-tags/discussions/164
There have been many discussions in the forums on how to improve this functionality, and I understand that the developers have agreed that it will be improved at some point.
Do you see limitations with this feature that make it not suitable for your usage?

> I use the metadata from the published version, because I'll only need the information from the published version to cite. But I keep the arXiv link in the URL page in case I want to share the paper with someone without access to the full text paper.

I understand that the assumption here is that the citation will never include the URL (arXiv URL here)?
Also that you will still be able to share the arXiv URL when you share the paper? How do you share the paper?

> It's a good idea to provide an alternative way to treat the URLs, as you mentioned.

At the moment, I keep the arXiv URL as a Web Link attachment, so that it does not have any effect on the metadata of the main item, as I still want to keep the URL of the final publication in the main item.
But I haven't tested how that works with sharing and referencing.

![image](https://github.com/user-attachments/assets/38900fcf-2e59-4301-b8ed-f04d4e0f81e2)
![image](https://github.com/user-attachments/assets/605767fd-cdcf-4a71-9376-5c5174be0f77)

**Comment by AllanChain** [comment]
> It is possible to link different items with the "Related" functionality.
> Do you see limitations with this feature that make it not suitable for your usage?

I see. I personally don't use this functionality. And if relating different items is already made possible by Actions and Tags plugin, we can focus on the workflow where one single parent item is used for both arXiv and published versions.

> assumption here is that the citation will never include the URL

Nice point. I agree that using a Web Link attachment is a better solution.

> How do you share the paper?

When I want to share the paper with someone, I will send the links in the email, or just send the PDF via IM apps. I don't know if there are other common ways to share a paper.

**Comment by mjthoraval** [comment]
Thank you very much.

"Related" is a Zotero feature. The Actions and Tags plugin only makes it more convenient to use from a right-click.
For example, to link the book and its chapters:
![image](https://github.com/user-attachments/assets/b475028a-3dfd-493e-ad3e-9f7c6bc1c62c)

But related items are still separate items. So it is different from your workflow, where you merge everything into a single parent item.

**Comment by AllanChain** [comment]
I just realized that for arXiv items added by Zotero browser extensions, there's already a "arXiv.org Snapshot" item containing the arXiv URL. Maybe I will create a Web Link attachment only when there's no snapshot saved.

**Comment by AllanChain** [comment]
Closing as completed with release v0.2.0
