### ISSUE TITLE
[Feature Requirement] update to the latest preprinted version.

### ISSUE THREAD

**Issue by 0x1orz** [AllanChain/zotero-arxiv-workflow#4]
To click `Updated to a published one`, it seems to only update the published. When the paper has not been published, the latest preprinted version may be an alternative.

**Comment by AllanChain** [comment]
That is a good idea! But I think it's better adding a menu option for preprint items to update arXiv papers. Adding a preprint PDF to an item for published paper would be confusing.

**Comment by 0x1orz** [comment]
to update [the arXiv v2 paper](https://arxiv.org/abs/2310.03842v2) to the v3, that does not work. It makes sense that  forcing to download the latest version to update or replace the local paper.
