### ISSUE TITLE
Unable to Locate Official Conference Paper Version  for 2305.14314

### ISSUE THREAD

**Issue by seifer08ms** [AllanChain/zotero-arxiv-workflow#8]
# Description:

I am experiencing an issue with the plugin where it is unable to successfully find [the official version](https://proceedings.neurips.cc/paper_files/paper/2023/hash/1feb87871436031bdc0f2beaa62a049b-Abstract-Conference.html) of the [QLoRA paper](http://arxiv.org/abs/2305.14314). Despite the publication information being present in the bitex on the arXiv page, the plugin does not find it.

<img width="521" alt="image" src="https://github.com/user-attachments/assets/6dfb92f7-bebc-4e1d-8625-c5ddd02f986f">

# Additional Information:

Plugin version: 0.2.2
zotero version:  7.0.1
os version:  mac  14  m1  
arXiv page link: http://arxiv.org/abs/2305.14314
Publication information: https://proceedings.neurips.cc/paper_files/paper/2023/hash/1feb87871436031bdc0f2beaa62a049b-Abstract-Conference.html

**Comment by AllanChain** [comment]
This is a known issue, as noted in README:

> It is not trivial to correctly find the published version. If it fails, you'd better add the journal article item manually and use the merge feature this plugin provides.

The plugin currently uses two sources to find the updated or published version: arXiv page and semantic scholar. If you know any other reliable sources, please tell me and I will look into it.

**Comment by seifer08ms** [comment]
> This is a known issue, as noted in README:
> 
> > It is not trivial to correctly find the published version. If it fails, you'd better add the journal article item manually and use the merge feature this plugin provides.
> 
> The plugin currently uses two sources to find the updated or published version: arXiv page and semantic scholar. If you know any other reliable sources, please tell me and I will look into it.

Thanks for your reply. I found the [doc](https://papermemory.org/features/#preprint-matching) of papermemory to describe how they match the preprint and the published one.
