### ISSUE TITLE
Hope a branch for Zotero 6

### ISSUE THREAD

**Issue by RonghaiHe** [AllanChain/zotero-arxiv-workflow#9]
Thanks for your contribution at first. However, I get accustomed to Zotero 6 and regretfully this extension is only for Zotero 7 now. Hope to obtain this kind of extension for Zotero 6. Thank you so much.

**Comment by AllanChain** [comment]
Sorry, but supporting both Zotero 6 and 7 is not trivial. I'm not using Zotero 6 and I have no motivation to support Zotero 6. However, if anyone is interested in implementing this, PRs are always welcomed.
